icons = {
    "athletics": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/athletics.png",
    "wnba": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/wnba.png",
    "nba": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/nba.png",
    
    "basketball": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/basketball.png",
    "ncaa men": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ncaa_men.png",
    "nhl": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/nhl.png",
    "nfl": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/nfl.png",
    
    "cfb": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/cfb.png",
    "ncaaf": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ncaaf.png",
    "football": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/football.png",
    "american football": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/american_football.png",
    "cfl": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/cfl.png",
    "mlb": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/mlb.jpg",
    "baseball": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/baseball.png",
    "formula-1": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/f_1.png",
    "f1": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/f_1.png",
    "motor-sports": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/motorsports.png",
    "motorsports": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/motorsports.png",
    "motor sports": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/motorsports.png",
    "motogp": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/moto_gp.png",
    "moto-gp": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/moto_gp.png",
    "horse racing": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/horse_racing.png",
    "racing": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/racing.png",
    "boxing": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/boxing.png",
    "mma-boxing": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/mma_boxing.png",
    "mma": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/mma.png",
    "ufc": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ufc.png",
    "cicket": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/cicket.png",
    "darts": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/darts.png",
    "soccer": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/soccer.png",
    "bundesliga": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/soccer.png",
    "tennis": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/tennis.png",
    "afl": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/afl.png",
    "rugby": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/rugby.png",
    "rugby union": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/rugby.png",
    "golf": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/golf.png",
    "squash":"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/squash.png",
    "volleyball" :"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/volleyball.png",
    "snooker":"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/snooker.png",
    "wwe":"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/wwe.png",
    "wrestling":"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/wwe.png.png",
    "ice hockey":"special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ice_hockey.png",
    "ncaah": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ncaa_h.png",
    "tv": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/tv.png",
    "tv shows": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/tv.png",
    "ski jumping": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ski_jumping.png",
    "handball": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/handball.png",
    "cycling": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/cycling.png",
    "ppv": "special://home/addons/plugin.video.jet_guide/resources/skins/default/720p/media/sports/ppv.png",
}